name: Build and Deploy
on:
  push:
    branches:
      - Fall20
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.5
    - run: julia -e '
            using Pkg;
            Pkg.add(["NodeJS", "JSON", "Franklin"]);
            using NodeJS;
            cd("website");
            run(`$(npm_cmd()) install highlight.js`);
            using Franklin;
            optimize();
            mkdir("__site2");
            mv("__site", "__site2/Fall20");
            write("__site2/index.html", """
                <!DOCTYPE html>
                <html>
                <head><meta charset="utf-8"><script>
                window.location.href=\"Fall20\"</script></head>
                <body></body></html>""");'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: website/__site2
